### ISSUE TITLE
About the loss

### ISSUE THREAD

**Issue by jiaaihhy** [YapengTian/TDAN-VSR-CVPR-2020#42]
In your paper, you have said that the loss is L1Loss, but in your code, the loss is MSELoss(), Is there something wrong?
And in your paper, the weight of the reconstruct loss and the aligned loss is 1 and 1, but in the code, the weight is 1 and 0.25?Can you make it clearily?
Thank you !

**Comment by YapengTian** [comment]
You might refer to the early arxiv version (2018). Please check the CVPR 20 version: https://openaccess.thecvf.com/content_CVPR_2020/papers/Tian_TDAN_Temporally-Deformable_Alignment_Network_for_Video_Super-Resolution_CVPR_2020_paper.pdf. From Eqs. 6, 7, 8, we can see that we used MSELoss for training. In addition, there is a factor (1/2N) in Eq. 6. Since we have 4 supporting frames, we compute alignment loss for each frame. It means that the factor is 1/4=0.25.

**Comment by jiaaihhy** [comment]
such is the case.
Thank you for your reply.
